site_name: UTIC❖{desarrollo}
site_url: https://josesagaz.github.io
site_author: Jose Sagaz
site_description: My experimental projects with free software
nav:
  - Inicio: index.md
  - About: about.md
  - Dev: desarrollo.md
theme: 
  name: mkdocs
  custom_dir: custom_theme/
#  nav_style: dark
  shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s

  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - php
  locale: es

